"""Writes src/data/mark.ts: the /O mark as outlines.

The O is Source Serif 4's own glyph, instanced at the font's largest optical
size (opsz 60) and weight 600 from the self-hosted file in public/fonts. The
slash is not the font's: the font draws it at about 73deg, and the page has one
angle, 70deg, so it is redrawn at that angle with the glyph's stem width and
height. The O sits GAP font units further from the slash than the typeset pair
would, measured at their closest approach.

It also writes public/favicon.svg: the same two outlines, so the tab shows the
logo, emboldened by an even stroke in each shape's own colour. At 16px the
display cut's hairlines would otherwise be under a pixel wide.

Outlines rather than text, so the mark does not wait for the web font and can be
rasterised on the card at build, where there is no font at all.

Run once after changing the font or the spacing (needs fontTools and brotli):
    python3 scripts/mark-outlines.py
"""
import math
from pathlib import Path

from fontTools.pens.basePen import BasePen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / 'public/fonts/source-serif-4-opsz-normal.woff2'
OUT = ROOT / 'src/data/mark.ts'
FAVICON = ROOT / 'public/favicon.svg'

AXES = {'opsz': 60, 'wght': 600}
FAV_STROKE = 1.6  # mark units of stroke on both favicon shapes
ANGLE = 70  # degrees from the horizontal, --slash in global.css
GAP = 80  # font units added to the typeset pair's closest approach
K = 0.05  # 1000 font units -> 50 mark units

font = TTFont(FONT)
cmap = font.getBestCmap()
glyphs = instantiateVariableFont(font, AXES).getGlyphSet()
slash_name, o_name = cmap[ord('/')], cmap[ord('O')]


class Points(BasePen):
    """Samples an outline into points, quadratic curves at 40 steps."""

    def __init__(self):
        super().__init__(None)
        self.pts, self.cur = [], None

    def _moveTo(self, p):
        self.cur = p
        self.pts.append(p)

    _lineTo = _moveTo

    def _qCurveToOne(self, c, p):
        (x0, y0) = self.cur
        for i in range(1, 41):
            t = i / 40
            self.pts.append(
                ((1 - t) ** 2 * x0 + 2 * (1 - t) * t * c[0] + t * t * p[0],
                 (1 - t) ** 2 * y0 + 2 * (1 - t) * t * c[1] + t * t * p[1]))
        self.cur = p

    def _closePath(self):
        pass


# The font's slash: a parallelogram, bottom edge y0, top edge y1, stem width w.
sp = Points()
glyphs[slash_name].draw(sp)
ys = sorted({y for _, y in sp.pts})
y0, y1 = ys[0], ys[-1]
bottom = sorted(x for x, y in sp.pts if y == y0)
top = sorted(x for x, y in sp.pts if y == y1)
w = bottom[-1] - bottom[0]
slash_adv = font['hmtx'][slash_name][0]

def outline(gs):
    pen = Points()
    gs[o_name].draw(pen)
    mid = (min(x for x, _ in pen.pts) + max(x for x, _ in pen.pts)) / 2
    return pen.pts, [(x, y) for x, y in pen.pts if x < mid]


op, o_left = outline(glyphs)


def closest(right_edge, o_dx, left=None):
    """Smallest horizontal distance from the slash's right edge to the O's left side."""
    return min(x + o_dx - right_edge(y) for x, y in (left or o_left) if y0 <= y <= y1)


def place(right_edge, target, left=None):
    """The O's x offset that puts its closest approach at target."""
    lo, hi = 0.0, 2000.0
    for _ in range(60):
        mid = (lo + hi) / 2
        lo, hi = (mid, hi) if closest(right_edge, mid, left) < target else (lo, mid)
    return hi


typeset = lambda y: bottom[-1] + (y - y0) * (top[-1] - bottom[-1]) / (y1 - y0)
target = closest(typeset, slash_adv) + GAP

run = (y1 - y0) / math.tan(math.radians(ANGLE))
redrawn = lambda y: w + (y - y0) * run / (y1 - y0)
o_dx = place(redrawn, target)


def n(v):
    return f'{round(v, 2):g}'


pen = SVGPathPen(None, ntos=n)
glyphs[o_name].draw(TransformPen(pen, (K, 0, 0, -K, o_dx * K, y1 * K)))
o_path = pen.getCommands()

corners = [(0, y0), (w, y0), (w + run, y1), (run, y1)]
slash_path = 'M' + ' '.join(f'{n(x * K)} {n((y1 - y) * K)}' for x, y in corners) + 'Z'

width = (o_dx + max(x for x, _ in op)) * K
height = (y1 - y0) * K
o_ys = [y for _, y in op]
o_mid = (y1 - (min(o_ys) + max(o_ys)) / 2) * K

OUT.write_text(f"""/**
 * The /O mark as outlines. Generated by scripts/mark-outlines.py; do not edit by hand.
 *
 * The O is Source Serif 4's own glyph at opsz {AXES['opsz']}, weight {AXES['wght']}. The slash is redrawn
 * at {ANGLE}deg, the page's one angle, with the font's stem width and height; the O
 * sits {GAP} font units further from it than the typeset pair would. Outlines, so
 * the mark never waits for the web font and the card can rasterise it at build.
 */

/** The mark's box. The ink fills it edge to edge. */
export const MARK_BOX = {{ w: {n(width)}, h: {n(height)} }} as const;

/** The O's vertical centre in the box, for centring on the letter rather than the slash's descent. */
export const MARK_O_MID = {n(o_mid)};

/** The slash, a parallelogram at {ANGLE}deg. */
export const MARK_SLASH = '{slash_path}';

/** The O, Source Serif 4's outline. Filled, with its counter as a second contour. */
export const MARK_O = '{o_path}';
""")
# The favicon: the logo's own outlines on a 32-unit linen square, each shape
# stroked in its own colour so the whole mark thickens evenly.
fav_w = width + FAV_STROKE
fav_h = height + FAV_STROKE
scale = 28 / fav_w
FAVICON.write_text(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" role="img" aria-label="Slash O">\n'
    '  <rect width="32" height="32" fill="#e4dfd1"/>\n'
    f'  <g transform="translate({n(2 + FAV_STROKE / 2 * scale)} {n((32 - fav_h * scale) / 2 + FAV_STROKE / 2 * scale)}) scale({round(scale, 5)})"'
    f' stroke-width="{FAV_STROKE}" stroke-linejoin="round">\n'
    f'    <path d="{slash_path}" fill="#9c4b2f" stroke="#9c4b2f"/>\n'
    f'    <path d="{o_path}" fill="#24302b" stroke="#24302b"/>\n'
    '  </g>\n'
    '</svg>\n'
)

print(f'wrote {OUT.relative_to(ROOT)}: {n(width)} x {n(height)}')
